"""
SQLite operational data layer for KazakhAI_ML_Gemini.

Standard-library `sqlite3` only - no ORM or external database dependency.
Persists satellite observations, pollution detections, forecasts, infrastructure
assets, risk scores, energy impact estimates, weather history and sea-level records,
and seeds itself from the verified JSON checkpoints generated by the AI pipeline.
"""

from __future__ import annotations

import os
import json
import sqlite3
import logging
import threading
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Dict, List, Optional, Iterator

logging.basicConfig(level=logging.INFO, format="%(levelname)s: [%(name)s] %(message)s")
logger = logging.getLogger("CaspianSQLiteStorage")


# A single RLock serializes every sqlite operation AND each full refresh cycle.
# Without it, the background scheduler thread and the FastAPI request threads can
# interleave statements/transactions on the same connection, which surfaces as
# sqlite3 "bad parameter or other API misuse" errors in production (e.g. Railway).
_DB_LOCK = threading.RLock()


class _ThreadSafeConnection:
    """Wraps a sqlite3.Connection so every call is executed under _DB_LOCK.

    The app is multi-threaded (FastAPI threadpool + background scheduler) while
    sharing one SQLite connection (check_same_thread=False). Python's sqlite3
    serializes individual C calls, but statement *sequences* (read while another
    thread commits) can still raise SQLITE_MISUSE, so we guard at this level too.
    """

    _LOCKED = frozenset({"execute", "executemany", "executescript", "commit", "rollback", "close", "cursor"})

    def __init__(self, conn: sqlite3.Connection):
        self._conn = conn

    def __getattr__(self, name: str) -> Any:
        attr = getattr(self._conn, name)
        if name in self._LOCKED:
            def locked(*args, **kwargs):
                with _DB_LOCK:
                    return attr(*args, **kwargs)
            return locked
        return attr


def default_db_path() -> Path:
    """Resolves the SQLite database location, honouring platform config.

    Precedence:
      1. DATABASE_PATH - absolute or relative path to the database file
         (set this to a Railway volume mount for persistent storage).
      2. DATA_DIR      - directory that will hold the database file.
      3. Repo-relative ./data/kazakh_ai.db (local development default).
    """
    env_path = os.environ.get("DATABASE_PATH")
    if env_path:
        return Path(env_path)
    data_dir = os.environ.get("DATA_DIR")
    base = Path(data_dir) if data_dir else Path(__file__).resolve().parent.parent.parent / "data"
    return base / "kazakh_ai.db"


DB_PATH = default_db_path()

SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS schema_version (
    version INTEGER PRIMARY KEY,
    applied_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS incidents (
    incident_id TEXT PRIMARY KEY,
    location_name TEXT,
    coordinates_lat REAL,
    coordinates_lon REAL,
    pollution_type TEXT,
    size_km2 REAL,
    toxicity_score REAL,
    severity_index REAL,
    detection_confidence REAL,
    priority_score REAL,
    urgency_classification TEXT,
    coastline_distance_m REAL,
    population_density_sqkm REAL,
    in_protected_ecosystem_zone INTEGER,
    economic_impact_estimate_usd REAL,
    forecast_spread_rate_km2_day REAL,
    status TEXT,
    detected_at TEXT
);

CREATE TABLE IF NOT EXISTS forecasts (
    forecast_id INTEGER PRIMARY KEY AUTOINCREMENT,
    incident_id TEXT NOT NULL,
    horizon_week INTEGER,
    forecast_day REAL,
    centroid_lat REAL,
    centroid_lon REAL,
    dispersion_radius_km REAL,
    spread_area_km2 REAL,
    remaining_mass_tons REAL,
    active_fraction REAL,
    beached_fraction REAL,
    confidence REAL,
    FOREIGN KEY (incident_id) REFERENCES incidents(incident_id)
);

CREATE TABLE IF NOT EXISTS heatmap_cells (
    cell_id TEXT PRIMARY KEY,
    coordinates_lat REAL,
    coordinates_lon REAL,
    bounding_box TEXT,
    threat_severity_score REAL,
    zone_classification TEXT,
    layer_breakdown TEXT
);

CREATE TABLE IF NOT EXISTS infrastructure (
    asset_id TEXT PRIMARY KEY,
    name TEXT,
    category TEXT,
    subcategory TEXT,
    country TEXT,
    coordinates_lat REAL,
    coordinates_lon REAL,
    replacement_value_usd REAL,
    description TEXT
);

CREATE TABLE IF NOT EXISTS risk_scores (
    risk_id INTEGER PRIMARY KEY AUTOINCREMENT,
    incident_id TEXT NOT NULL,
    asset_id TEXT NOT NULL,
    distance_km REAL,
    arrival_days REAL,
    threat_level TEXT,
    risk_score REAL,
    inspection_priority TEXT,
    computed_at TEXT,
    UNIQUE(incident_id, asset_id),
    FOREIGN KEY (incident_id) REFERENCES incidents(incident_id),
    FOREIGN KEY (asset_id) REFERENCES infrastructure(asset_id)
);

CREATE TABLE IF NOT EXISTS energy_impacts (
    impact_id INTEGER PRIMARY KEY AUTOINCREMENT,
    incident_id TEXT NOT NULL,
    asset_id TEXT NOT NULL,
    infrastructure_protection REAL,
    maintenance_savings_usd REAL,
    avoided_downtime_hours REAL,
    operational_disruption_avoided_usd REAL,
    environmental_benefit REAL,
    carbon_impact_tons_co2e REAL,
    energy_impact_score REAL,
    computed_at TEXT,
    UNIQUE(incident_id, asset_id),
    FOREIGN KEY (incident_id) REFERENCES incidents(incident_id),
    FOREIGN KEY (asset_id) REFERENCES infrastructure(asset_id)
);

CREATE TABLE IF NOT EXISTS anomaly_masks (
    anomaly_id INTEGER PRIMARY KEY AUTOINCREMENT,
    week_start TEXT,
    coordinates_lat REAL,
    coordinates_lon REAL,
    sar_z_score REAL,
    water_quality_z_score REAL,
    chlorophyll REAL,
    turbidity REAL,
    cdom REAL,
    sar_anomaly INTEGER,
    water_quality_anomaly INTEGER,
    confidence REAL,
    predicted_type TEXT
);

CREATE TABLE IF NOT EXISTS sea_level (
    period TEXT PRIMARY KEY,
    level_cm REAL,
    change_cm REAL,
    trend TEXT
);

CREATE TABLE IF NOT EXISTS trends (
    trend_id INTEGER PRIMARY KEY AUTOINCREMENT,
    metric TEXT,
    period_start TEXT,
    period_end TEXT,
    value REAL,
    category TEXT
);

CREATE TABLE IF NOT EXISTS weather_history (
    record_id INTEGER PRIMARY KEY AUTOINCREMENT,
    observed_at TEXT,
    coordinates_lat REAL,
    coordinates_lon REAL,
    wind_speed_ms REAL,
    wind_direction_deg REAL,
    rainfall_mm REAL,
    sea_surface_temp_c REAL,
    source TEXT
);

CREATE INDEX IF NOT EXISTS idx_forecasts_incident ON forecasts(incident_id);
CREATE INDEX IF NOT EXISTS idx_risk_asset ON risk_scores(asset_id);
CREATE INDEX IF NOT EXISTS idx_risk_incident ON risk_scores(incident_id);
CREATE INDEX IF NOT EXISTS idx_energy_incident ON energy_impacts(incident_id);
CREATE INDEX IF NOT EXISTS idx_anomaly_week ON anomaly_masks(week_start);
CREATE INDEX IF NOT EXISTS idx_weather_time ON weather_history(observed_at);
"""

SEED_VERSION = 1


class CaspianDatabase:
    """Thin, dependency-free wrapper around a persistent SQLite connection."""

    def __init__(self, db_path: Optional[Path] = None):
        self.db_path = Path(db_path) if db_path else default_db_path()
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        # check_same_thread=False: FastAPI executes sync endpoints in a threadpool,
        # while the connection is created in the main thread during lifespan startup.
        raw_conn = sqlite3.connect(str(self.db_path), check_same_thread=False)
        raw_conn.row_factory = sqlite3.Row
        self.conn = _ThreadSafeConnection(raw_conn)
        with _DB_LOCK:
            raw_conn.execute("PRAGMA foreign_keys = ON;")
            raw_conn.execute("PRAGMA journal_mode = WAL;")
            raw_conn.executescript(SCHEMA_SQL)
            raw_conn.commit()
        logger.info(f"Connected to SQLite operational database: {self.db_path}")

    @contextmanager
    def locked(self) -> Iterator[None]:
        """Context manager that serializes an entire multi-statement workflow.

        Use it around full refresh cycles so the background scheduler and the
        admin refresh endpoint never interleave writes on the shared connection.
        """
        with _DB_LOCK:
            yield

    def close(self) -> None:
        with _DB_LOCK:
            self._close()

    def _close(self) -> None:
        try:
            self.conn._conn.close()
        except sqlite3.ProgrammingError:
            pass

    def _schema_version(self) -> int:
        row = self.conn.execute("SELECT COALESCE(MAX(version), 0) FROM schema_version").fetchone()
        return int(row[0])

    def mark_seeded(self, version: int = SEED_VERSION) -> None:
        if self._schema_version() < version:
            self.conn.execute("INSERT INTO schema_version (version) VALUES (?)", (version,))
            self.conn.commit()

    def is_seeded(self) -> bool:
        return self._schema_version() >= SEED_VERSION

    # ------------------------------------------------------------------ write
    def upsert_incident(self, inc: Dict[str, Any]) -> None:
        cols = (
            "incident_id", "location_name", "coordinates_lat", "coordinates_lon",
            "pollution_type", "size_km2", "toxicity_score", "severity_index",
            "detection_confidence", "priority_score", "urgency_classification",
            "coastline_distance_m", "population_density_sqkm", "in_protected_ecosystem_zone",
            "economic_impact_estimate_usd", "forecast_spread_rate_km2_day", "status", "detected_at",
        )
        vals = [inc.get(c) for c in cols]
        placeholders = ", ".join(["?"] * len(cols))
        updates = ", ".join([f"{c}=excluded.{c}" for c in cols if c != "incident_id"])
        self.conn.execute(
            f"INSERT INTO incidents ({', '.join(cols)}) VALUES ({placeholders}) "
            f"ON CONFLICT(incident_id) DO UPDATE SET {updates}",
            vals,
        )

    def insert_forecast(self, f: Dict[str, Any]) -> None:
        self.conn.execute(
            "INSERT INTO forecasts (incident_id, horizon_week, forecast_day, centroid_lat, centroid_lon, "
            "dispersion_radius_km, spread_area_km2, remaining_mass_tons, active_fraction, beached_fraction, confidence) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            (f.get("incident_id"), f.get("horizon_week"), f.get("forecast_day"), f.get("centroid_lat"),
             f.get("centroid_lon"), f.get("dispersion_radius_km"), f.get("spread_area_km2"),
             f.get("remaining_mass_tons"), f.get("active_fraction"), f.get("beached_fraction"), f.get("confidence")),
        )

    def clear_forecasts(self, incident_id: str) -> None:
        self.conn.execute("DELETE FROM forecasts WHERE incident_id = ?", (incident_id,))

    def upsert_heatmap_cell(self, cell: Dict[str, Any]) -> None:
        self.conn.execute(
            "INSERT INTO heatmap_cells (cell_id, coordinates_lat, coordinates_lon, bounding_box, "
            "threat_severity_score, zone_classification, layer_breakdown) VALUES (?, ?, ?, ?, ?, ?, ?) "
            "ON CONFLICT(cell_id) DO UPDATE SET threat_severity_score=excluded.threat_severity_score, "
            "zone_classification=excluded.zone_classification, layer_breakdown=excluded.layer_breakdown",
            (cell.get("cell_id"), cell.get("coordinates_lat"), cell.get("coordinates_lon"),
             json.dumps(cell.get("bounding_box")), cell.get("threat_severity_score"),
             cell.get("zone_classification"), json.dumps(cell.get("layer_breakdown"))),
        )

    def upsert_infrastructure(self, asset: Dict[str, Any]) -> None:
        self.conn.execute(
            "INSERT INTO infrastructure (asset_id, name, category, subcategory, country, "
            "coordinates_lat, coordinates_lon, replacement_value_usd, description) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) "
            "ON CONFLICT(asset_id) DO UPDATE SET name=excluded.name, category=excluded.category, "
            "subcategory=excluded.subcategory, country=excluded.country, "
            "coordinates_lat=excluded.coordinates_lat, coordinates_lon=excluded.coordinates_lon, "
            "replacement_value_usd=excluded.replacement_value_usd, description=excluded.description",
            (asset.get("asset_id"), asset.get("name"), asset.get("category"), asset.get("subcategory"),
             asset.get("country"), asset.get("coordinates_lat"), asset.get("coordinates_lon"),
             asset.get("replacement_value_usd"), asset.get("description")),
        )

    def upsert_risk_score(self, r: Dict[str, Any]) -> None:
        self.conn.execute(
            "INSERT INTO risk_scores (incident_id, asset_id, distance_km, arrival_days, threat_level, "
            "risk_score, inspection_priority, computed_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?) "
            "ON CONFLICT(incident_id, asset_id) DO UPDATE SET distance_km=excluded.distance_km, "
            "arrival_days=excluded.arrival_days, threat_level=excluded.threat_level, "
            "risk_score=excluded.risk_score, inspection_priority=excluded.inspection_priority, "
            "computed_at=excluded.computed_at",
            (r.get("incident_id"), r.get("asset_id"), r.get("distance_km"), r.get("arrival_days"),
             r.get("threat_level"), r.get("risk_score"), r.get("inspection_priority"), r.get("computed_at")),
        )

    def upsert_energy_impact(self, e: Dict[str, Any]) -> None:
        self.conn.execute(
            "INSERT INTO energy_impacts (incident_id, asset_id, infrastructure_protection, "
            "maintenance_savings_usd, avoided_downtime_hours, operational_disruption_avoided_usd, "
            "environmental_benefit, carbon_impact_tons_co2e, energy_impact_score, computed_at) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) "
            "ON CONFLICT(incident_id, asset_id) DO UPDATE SET "
            "infrastructure_protection=excluded.infrastructure_protection, "
            "maintenance_savings_usd=excluded.maintenance_savings_usd, "
            "avoided_downtime_hours=excluded.avoided_downtime_hours, "
            "operational_disruption_avoided_usd=excluded.operational_disruption_avoided_usd, "
            "environmental_benefit=excluded.environmental_benefit, "
            "carbon_impact_tons_co2e=excluded.carbon_impact_tons_co2e, "
            "energy_impact_score=excluded.energy_impact_score, computed_at=excluded.computed_at",
            (e.get("incident_id"), e.get("asset_id"), e.get("infrastructure_protection"),
             e.get("maintenance_savings_usd"), e.get("avoided_downtime_hours"),
             e.get("operational_disruption_avoided_usd"), e.get("environmental_benefit"),
             e.get("carbon_impact_tons_co2e"), e.get("energy_impact_score"), e.get("computed_at")),
        )

    def insert_anomaly(self, a: Dict[str, Any]) -> None:
        self.conn.execute(
            "INSERT INTO anomaly_masks (week_start, coordinates_lat, coordinates_lon, sar_z_score, "
            "water_quality_z_score, chlorophyll, turbidity, cdom, sar_anomaly, water_quality_anomaly, "
            "confidence, predicted_type) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            (a.get("week_start"), a.get("coordinates_lat"), a.get("coordinates_lon"), a.get("sar_z_score"),
             a.get("water_quality_z_score"), a.get("chlorophyll"), a.get("turbidity"), a.get("cdom"),
             int(bool(a.get("sar_anomaly"))), int(bool(a.get("water_quality_anomaly"))),
             a.get("confidence"), a.get("predicted_type")),
        )

    def upsert_sea_level(self, s: Dict[str, Any]) -> None:
        self.conn.execute(
            "INSERT INTO sea_level (period, level_cm, change_cm, trend) VALUES (?, ?, ?, ?) "
            "ON CONFLICT(period) DO UPDATE SET level_cm=excluded.level_cm, change_cm=excluded.change_cm, "
            "trend=excluded.trend",
            (s.get("period"), s.get("level_cm"), s.get("change_cm"), s.get("trend")),
        )

    def insert_trend(self, t: Dict[str, Any]) -> None:
        self.conn.execute(
            "INSERT INTO trends (metric, period_start, period_end, value, category) VALUES (?, ?, ?, ?, ?)",
            (t.get("metric"), t.get("period_start"), t.get("period_end"), t.get("value"), t.get("category")),
        )

    def clear_trends(self) -> None:
        self.conn.execute("DELETE FROM trends")

    def insert_weather(self, w: Dict[str, Any]) -> None:
        self.conn.execute(
            "INSERT INTO weather_history (observed_at, coordinates_lat, coordinates_lon, wind_speed_ms, "
            "wind_direction_deg, rainfall_mm, sea_surface_temp_c, source) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
            (w.get("observed_at"), w.get("coordinates_lat"), w.get("coordinates_lon"), w.get("wind_speed_ms"),
             w.get("wind_direction_deg"), w.get("rainfall_mm"), w.get("sea_surface_temp_c"), w.get("source")),
        )

    # ------------------------------------------------------------------ read
    def all_incidents(self) -> List[Dict[str, Any]]:
        rows = self.conn.execute(
            "SELECT * FROM incidents ORDER BY priority_score DESC, detected_at DESC"
        ).fetchall()
        return [dict(r) for r in rows]

    def incident_by_id(self, incident_id: str) -> Optional[Dict[str, Any]]:
        row = self.conn.execute("SELECT * FROM incidents WHERE incident_id = ?", (incident_id,)).fetchone()
        return dict(row) if row else None

    def forecasts_for(self, incident_id: str) -> List[Dict[str, Any]]:
        rows = self.conn.execute(
            "SELECT * FROM forecasts WHERE incident_id = ? ORDER BY horizon_week, forecast_day", (incident_id,)
        ).fetchall()
        return [dict(r) for r in rows]

    def all_assets(self) -> List[Dict[str, Any]]:
        rows = self.conn.execute("SELECT * FROM infrastructure ORDER BY category, name").fetchall()
        return [dict(r) for r in rows]

    def risk_scores(self, incident_id: Optional[str] = None) -> List[Dict[str, Any]]:
        if incident_id:
            rows = self.conn.execute(
                "SELECT * FROM risk_scores WHERE incident_id = ? ORDER BY risk_score DESC", (incident_id,)
            ).fetchall()
        else:
            rows = self.conn.execute("SELECT * FROM risk_scores ORDER BY risk_score DESC").fetchall()
        return [dict(r) for r in rows]

    def energy_impacts(self, incident_id: Optional[str] = None) -> List[Dict[str, Any]]:
        if incident_id:
            rows = self.conn.execute(
                "SELECT * FROM energy_impacts WHERE incident_id = ? ORDER BY energy_impact_score DESC",
                (incident_id,),
            ).fetchall()
        else:
            rows = self.conn.execute("SELECT * FROM energy_impacts ORDER BY energy_impact_score DESC").fetchall()
        return [dict(r) for r in rows]

    def heatmap_cells(self) -> List[Dict[str, Any]]:
        rows = self.conn.execute("SELECT * FROM heatmap_cells ORDER BY threat_severity_score DESC").fetchall()
        return [dict(r) for r in rows]

    def anomaly_masks(self, week_start: Optional[str] = None) -> List[Dict[str, Any]]:
        if week_start:
            rows = self.conn.execute(
                "SELECT * FROM anomaly_masks WHERE week_start = ? ORDER BY confidence DESC", (week_start,)
            ).fetchall()
        else:
            rows = self.conn.execute("SELECT * FROM anomaly_masks ORDER BY week_start, confidence DESC").fetchall()
        return [dict(r) for r in rows]

    def sea_level(self) -> List[Dict[str, Any]]:
        rows = self.conn.execute("SELECT * FROM sea_level ORDER BY period").fetchall()
        return [dict(r) for r in rows]

    def trends(self, category: Optional[str] = None) -> List[Dict[str, Any]]:
        if category:
            rows = self.conn.execute(
                "SELECT * FROM trends WHERE category = ? ORDER BY period_start", (category,)
            ).fetchall()
        else:
            rows = self.conn.execute("SELECT * FROM trends ORDER BY period_start").fetchall()
        return [dict(r) for r in rows]

    def stats(self) -> Dict[str, Any]:
        n_inc = self.conn.execute("SELECT COUNT(*) FROM incidents").fetchone()[0]
        n_for = self.conn.execute("SELECT COUNT(*) FROM forecasts").fetchone()[0]
        n_anom = self.conn.execute("SELECT COUNT(*) FROM anomaly_masks").fetchone()[0]
        n_risk = self.conn.execute("SELECT COUNT(*) FROM risk_scores").fetchone()[0]
        n_energy = self.conn.execute("SELECT COUNT(*) FROM energy_impacts").fetchone()[0]
        n_assets = self.conn.execute("SELECT COUNT(*) FROM infrastructure").fetchone()[0]
        n_cells = self.conn.execute("SELECT COUNT(*) FROM heatmap_cells").fetchone()[0]
        n_weather = self.conn.execute("SELECT COUNT(*) FROM weather_history").fetchone()[0]
        max_priority = self.conn.execute("SELECT COALESCE(MAX(priority_score), 0) FROM incidents").fetchone()[0]
        total_impact = self.conn.execute(
            "SELECT COALESCE(SUM(operational_disruption_avoided_usd), 0) FROM energy_impacts"
        ).fetchone()[0]
        total_savings = self.conn.execute(
            "SELECT COALESCE(SUM(maintenance_savings_usd), 0) FROM energy_impacts"
        ).fetchone()[0]
        by_type = {
            r["pollution_type"]: r["cnt"]
            for r in self.conn.execute(
                "SELECT pollution_type, COUNT(*) AS cnt FROM incidents GROUP BY pollution_type"
            ).fetchall()
        }
        return {
            "incidents": n_inc,
            "forecast_frames": n_for,
            "anomaly_masks": n_anom,
            "risk_scores": n_risk,
            "energy_impacts": n_energy,
            "infrastructure_assets": n_assets,
            "heatmap_cells": n_cells,
            "weather_records": n_weather,
            "max_priority_score": max_priority,
            "incidents_by_type": by_type,
            "total_maintenance_savings_usd": total_savings,
            "total_disruption_avoided_usd": total_impact,
        }

    def commit(self) -> None:
        self.conn.commit()


def load_checkpoint_json(rel_path: str) -> Dict[str, Any]:
    """Loads a checkpoint JSON relative to the checkpoints/ directory."""
    checkpoints_dir = Path(__file__).resolve().parent.parent / "checkpoints"
    with open(checkpoints_dir / rel_path, "r", encoding="utf-8") as f:
        return json.load(f)


def seed_from_checkpoints(db: CaspianDatabase, *, now: str = "2026-08-05T00:00:00Z") -> None:
    """
    Bootstraps the SQLite database from the verified AI pipeline checkpoints:
    ranked priority list, 30-day drift forecast and regional risk heatmap.
    Idempotent - safe to call on every server startup.
    """
    if db.is_seeded() and db.conn.execute("SELECT COUNT(*) FROM incidents").fetchone()[0] > 0:
        logger.info("Database already seeded - skipping checkpoint ingestion.")
        return

    with db.locked():
        _seed_from_checkpoints_locked(db, now=now)
    db.commit()
    logger.info("SQLite database bootstrap complete.")


def _seed_from_checkpoints_locked(db: CaspianDatabase, *, now: str) -> None:
    """Checkpoint ingestion body, executed under the database lock."""
    # --- 1. Incidents (from Step 17 priority engine) -------------------------
    try:
        priority = load_checkpoint_json("ranked_pollution_priority_list.json")
        for item in priority.get("ranked_pollution_list", []):
            coords = item.get("coordinates", [0.0, 0.0])
            breakdown = item.get("factor_breakdown", {})
            db.upsert_incident({
                "incident_id": item.get("incident_id"),
                "location_name": item.get("location_name"),
                "coordinates_lat": coords[0] if isinstance(coords, list) and len(coords) > 0 else None,
                "coordinates_lon": coords[1] if isinstance(coords, list) and len(coords) > 1 else None,
                "pollution_type": _type_from_incident(item),
                "size_km2": breakdown.get("pollution_size_km2"),
                "toxicity_score": breakdown.get("toxicity_index"),
                "detection_confidence": None if breakdown.get("ai_detection_confidence") is None
                else round(float(breakdown.get("ai_detection_confidence", 0)) / 100.0, 4),
                "priority_score": item.get("priority_score"),
                "urgency_classification": item.get("urgency_classification"),
                "coastline_distance_m": breakdown.get("coastline_distance_m"),
                "population_density_sqkm": breakdown.get("population_density_sqkm"),
                "in_protected_ecosystem_zone": int(bool(breakdown.get("protected_ecosystem_zone"))),
                "economic_impact_estimate_usd": breakdown.get("economic_loss_usd"),
                "forecast_spread_rate_km2_day": breakdown.get("forecast_spread_km2_day"),
                "status": "active",
                "detected_at": now,
            })
        logger.info(f"Seeded {len(priority.get('ranked_pollution_list', []))} incidents from priority checkpoint.")
    except FileNotFoundError:
        logger.warning("ranked_pollution_priority_list.json not found - skipping incident seed.")

    # --- 2. Forecast frames (from Step 16 drift engine) ----------------------
    try:
        drift = load_checkpoint_json("lagrangian_drift_30day_forecast.json")
        incident_id = db.conn.execute(
            "SELECT incident_id FROM incidents ORDER BY priority_score DESC LIMIT 1"
        ).fetchone()
        target_id = incident_id[0] if incident_id else "SPILL_2026_001_BAKU_HARBOR"
        db.clear_forecasts(target_id)
        n_weeks = [0, 7, 14, 21, 28]
        weeks_frame = [f for f in drift.get("trajectory_frames", []) if f.get("day", 0) in n_weeks]
        for idx, frame in enumerate(weeks_frame):
            active = float(frame.get("active_floating_particles", frame.get("active_particles", 0)))
            beached = float(frame.get("beached_shoreline_particles", frame.get("beached_particles", 0)))
            total = max(1.0, active + beached)
            db.insert_forecast({
                "incident_id": target_id,
                "horizon_week": idx,
                "forecast_day": frame.get("day", 0),
                "centroid_lat": frame.get("centroid_lat"),
                "centroid_lon": frame.get("centroid_lon"),
                "dispersion_radius_km": frame.get("dispersion_radius_km"),
                "spread_area_km2": round(3.14159 * float(frame.get("dispersion_radius_km", 1.0)) ** 2, 2),
                "remaining_mass_tons": frame.get("remaining_floating_oil_tons"),
                "active_fraction": round(active / total, 4),
                "beached_fraction": round(beached / total, 4),
                "confidence": round(max(0.05, 0.95 - 0.01 * float(frame.get("day", 0))), 4),
            })
        logger.info(f"Seeded {len(weeks_frame)} weekly forecast frames for incident {target_id}.")
    except FileNotFoundError:
        logger.warning("lagrangian_drift_30day_forecast.json not found - skipping forecast seed.")

    # --- 3. Regional risk heatmap (from Step 18 generator) -------------------
    try:
        heatmap = load_checkpoint_json("regional_risk_heatmap.json")
        for cell in heatmap.get("grid_cells", []):
            center = cell.get("coordinates_center", [0.0, 0.0])
            db.upsert_heatmap_cell({
                "cell_id": cell.get("cell_id"),
                "coordinates_lat": center[0] if len(center) > 0 else None,
                "coordinates_lon": center[1] if len(center) > 1 else None,
                "bounding_box": cell.get("bounding_box"),
                "threat_severity_score": cell.get("threat_severity_score"),
                "zone_classification": cell.get("zone_classification"),
                "layer_breakdown": cell.get("layer_breakdown"),
            })
        logger.info(f"Seeded {len(heatmap.get('grid_cells', []))} heatmap cells.")
    except FileNotFoundError:
        logger.warning("regional_risk_heatmap.json not found - skipping heatmap seed.")

    db.mark_seeded()


def _type_from_incident(item: Dict[str, Any]) -> str:
    """Infers a pollution class from the incident id / location, else defaults to hydrocarbon."""
    incident_id = str(item.get("incident_id", "")).lower()
    location = str(item.get("location_name", "")).lower()
    if "silt" in incident_id or "sediment" in location or "delta" in location:
        return "river_sediment"
    if "algae" in location or "bloom" in location:
        return "algal_bloom"
    if "lakebed" in location or "exposed" in location:
        return "exposed_contaminated_lakebed"
    if "runoff" in location or "industrial" in location:
        return "industrial_runoff"
    return "oil_hydrocarbon"
